version: '3'
services:
  postgres_1:
    image: postgres:11
  postgres_2:
    image: postgres:11
  tests:
    build: .
    image: norm
    depends_on:
      - postgres_1
      - postgres_2
    volumes:
      - .:/usr/src/app
    command: nimble test -c
  test:
    build: .
    image: norm
    depends_on:
      - postgres_1
      - postgres_2
    volumes:
      - .:/usr/src/app
    entrypoint: nim c -r
