repo_url: https://github.com/moigagoo/norm
edit_uri: edit/develop/docs/src/

theme:
  name: material
  palette:
    primary: white
    accent: pink
  logo: assets/pyramid.svg
  favicon: assets/pyramid.ico

extra:
  social:
    - type: github
      link: https://github.com/moigagoo/norm

markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - admonition

copyright: >
  <p>Created by <a href="https://github.com/moigagoo/">Constantine Molchanov</a>
  using <a href="https://foliant.rocks">Foliant</a>.</p>

  <p>Icons made by <a href="https://www.flaticon.com/authors/xnimrodx" title="xnimrodx">xnimrodx</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>.</p>